#!/bin/bash
domainHome=$1
packageHome=$2
profileDirPath=${packageHome}/etc/profile.d
packageName=${packageHome##*/}
profilePath=${profileDirPath}/${packageName}.sh
mkdir -p ${profileDirPath}
#echo "#${packageName%%_*}_HOME=${packageHome}" >> ${profilePath}
mkdir -p ${packageHome}/bin
cp ${packageHome}/maint/install_fst2tsf.sh ${packageHome}/bin
